### ISSUE TITLE
Remove smurf naming conventions on types

### ISSUE THREAD

**Issue by allansson** [AtmosphereMessaging/Cumulus#4]
There are a lot of types which begin with the prefix Nimbus (or soon to be Cumulus), e.g. NimbusSubscriptionMessageReceiver or INimbusMessageReceiver. 

It should be obvious to anyone that these classes are a part of Cumulus, making the prefixed naming convention useless. We should get rid of them. Type names should only convey information about what the implementation does.

**Comment by cbird** [comment]
Done in the same commit as the renaming of namespace Nimbus -> Cumulus 9fd4dd82f4316c10f85b39c3f20eb4fb3a9ca79f
